services:
  docs:
    image: whatsapp_api_local_docs
    container_name: whatsapp_api_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./whatsapp_api:/app/whatsapp_api:z
    ports:
      - '9000:9000'
    command: /start-docs
